name: Android CI (Feature to Main)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Restore local.properties
        run: echo "${{ secrets.BUILD_PROPERTIES }}" | base64 -d > local.properties

      - name: Create dummy keystore.properties
        run: |
          echo "storeFile=./dummy.jks" > keystore.properties
          echo "storePassword=dummy" >> keystore.properties
          echo "keyAlias=dummy" >> keystore.properties
          echo "keyPassword=dummy" >> keystore.properties
          touch dummy.jks

      - name: Run Lint
        run: ./gradlew lintDevDebug

      - name: Run Unit Tests
        run: ./gradlew testDevDebugUnitTest

      - name: Build Debug APK
        run: ./gradlew assembleDevDebug

      - name: Send Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
         SLACK_COLOR: '#FF0000'
         SLACK_USERNAME: 'SOOUM CI Bot'
         SLACK_TITLE: 'ğŸš¨ CI Build/Test Failed'
         SLACK_MESSAGE: 'SOOUM-AOS ë¹Œë“œ í˜¹ì€ í…ŒìŠ¤íŠ¸ê°€ ì‹¤íŒ¨í–ˆìŠµë‹ˆë‹¤. ì—ëŸ¬ ë¡œê·¸ë¥¼ í™•ì¸í•´ì£¼ì„¸ìš”.'
         SLACK_FOOTER: 'GitHub Actions'