name: Android CI/CD

on:
  push:
    branches:
      - 'develop-release'

jobs:
  firebase-dist:
    if: github.ref == 'refs/heads/develop-release'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Restore local.properties
        run: echo "${{ secrets.BUILD_PROPERTIES }}" | base64 -d > local.properties
        
      - name: Build Debug APK
        run: ./gradlew assembleDevDebug

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIAL }}
          groups: clib
          file: app/build/outputs/apk/dev/debug/app-dev-debug.apk
