name: Android Play Store Deploy (Draft)

on:
  push:
    branches:
      - 'release-prod' 

jobs:
  play-store-dist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Restore local.properties
        run: echo "${{ secrets.BUILD_PROPERTIES }}" | base64 -d > local.properties

      - name: Restore keystore.properties
        run: echo "${{ secrets.KEYSTORE_PROPERTIES }}" | base64 -d > keystore.properties

      - name: Restore Keystore File
        run: echo "${{ secrets.ANDROID_KEYSTORE_FILE }}" | base64 -d > upload-keystore.jks

      - name: Update keystore path
        run: echo "storeFile=../upload-keystore.jks" >> keystore.properties
        
      - name: Build Signed Release AAB
        run: ./gradlew bundleProdRelease -Dorg.gradle.jvmargs=-Xmx4608m
        
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.ANDROID_PUBLISHER_CREDENTIALS }}
          packageName: com.phew.sooum
          releaseFiles: app/build/outputs/bundle/prodRelease/app-prod-release.aab
          track: alpha
          status: draft
